// ********RoostGPT********
/*
Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test ui-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=
ROOST_METHOD_SIG_HASH=




*/

// ********RoostGPT********
using Xunit;
using Bunit;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Components;
using MyProject.Components; // Assuming namespace of the component

public class TodoItemTests : TestContext
{
    [Fact]
    public void TodoItem_ShowsCompleted_WhenParameterIsSet()
    {
        // Arrange
        var cut = RenderComponent<TodoItem>(parameters => parameters
            .Add(p => p.IsComplete, true));

        // Assert
        Assert.Contains("completed", cut.Find("div").ClassName);
    }

    [Fact]
    public void TodoItem_CheckboxReflects_IsCompleteParameter()
    {
        // Arrange
        var cut = RenderComponent<TodoItem>(parameters => parameters
            .Add(p => p.IsComplete, true));

        // Assert
        Assert.True(cut.Find("input").IsChecked);
    }

    [Fact]
    public void TodoItem_DisableDeleteButton_WhenProcessing()
    {
        // Arrange
        var cut = RenderComponent<TodoItem>(parameters => parameters
            .Add(p => p.IsProcessing, true));

        // Assert
        Assert.Contains("disabled", cut.Find("button").ClassName);
    }

    [Fact]
    public void TodoItem_Delete_IsInvoked_WhenButtonClicked()
    {
        // Arrange
        var invoked = false;
        var cut = RenderComponent<TodoItem>(parameters => parameters
            .Add(p => p.OnDelete, new EventCallback(() =>
            {
                invoked = true;
            })));

        // Act
        cut.Find("button").Click();

        // Assert
        Assert.True(invoked);
    }
}
